#!/usr/bin/env bash
# This script displays cript that configures an Ubuntu server with requirements.
# Requirements:
#localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
sed -i 's/157.240.11.35/8.8.8.8/g' /etc/hosts
cp -f ~/hosts.new /etc/hosts
